# Base configs
baseurl: "http://pa1-bi2.github.io/dollybirthday"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Happy Happy Birthday DOLLY"
subtitle: "Count your age by friends, not years. ...!"
author: " Pavan Kumar"
header:
 title: "Happy Birthday"
 subtitle: "Vidheya Gajjagouni"
footer:
 name: "Hey there, my name is Bittu"
 bio: "I thank each and everyone for spending your time for sending :)."
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/pa1_bi2"
  linkedin: "https://www.linkedin.com/in/pavan-kumar-b9032310a/"
  github: "https://www.github.com/pa-bi2"
